baseURL: https://kobybibas.github.io/
title: Koby Bibas
theme: PaperMod
paginate: 5
# googleAnalytics: G-7BWGX7L5F0

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # assets:
  #   favicon: favicon.ico

  # Home page
  homeInfoParams:
    title: Welcome 👋
    image:
      url: green-man-drawing-vector-cartoon-icon_53876-118118.jpg
      title: Me
    content: |
      - My name is Koby, a PhD student specializing in machine learning. My academic journey revolves around exploring the fascinating realms of computer vision and information theory. 
      - When I'm not immersed in the world of algorithms and data, you can find me indulging in my guilty pleasure - coffee and carbs.
      - In this website, I'm documenting my learning notes, paper summaries, and proof of concepts.
    social:
      align: left
      icons:
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=MYsSRvYAAAAJ&hl=iw"
        - name: github
          url: "https://github.com/kobybibas"
        - name: linkedin
          url: "https://www.linkedin.com/in/koby-bibas/"

  # Posts options
  showToc: true
  showReadingTime: true
  showWordCount: true
  showCodeCopyButtons: true
  cover:
    hidden: true
    hiddenInSingle: false
  editPost:
    URL: https://github.com/kobybibas/kobybibas.github.io/tree/main/content/
    Text: 📝 Suggest changes
    appendFilePath: true

  # Search options
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

# Enable search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
